id: P009275
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS18061
  title: ཡུལ་ལྷ་གཉན་པོའི་གསོལ་མཆོད་བསྐང་བཤགས་བྱ་ཚུལ།
  author: ''
  volumes:
    1038348a5adb40f9a3b6bbaddff095ed:
      image_group_id: I8LS18081
      title: ''
      volume_number: 1
      total_pages: 46
      base_file: v001.txt
