id: I822A88BC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T03:09:54+00:00'
last_modified: '2022-06-08T09:51:41.972878+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18061
  title: ཡུལ་ལྷ་གཉན་པོའི་གསོལ་མཆོད་བསྐང་བཤགས་བྱ་ཚུལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0A3D:
      image_group_id: I8LS18081
      title: ''
      total_pages: 46
      order: 1
      base_file: 0A3D.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
